name: Wikibot

on:
  workflow_dispatch:
  push:
    branches: [ main ] 

jobs:
  wikibot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Wikibot
        id: bot
        uses: "framewiki/wikibot@morph/initial-development"

      - name: Check for Changes
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV
          fi
      
      - name: Commit and Push Changes to Branch
        if: env.changes_detected == 'true'
        run: |
          git config user.name Wikibot
          git config user.email github-actions@github.com
          git commit -a -m "Changes by Wikibot" --no-verify
          git push origin HEAD:wikibot
